# agent/state.py
from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    target_os: str
    target_module: str
    symptom_type: str
    issue_type: str
    time_range_days: int

    # Point 1: Dynamic Query & Router State
    constructed_query: str          # Best-effort query string shown for logging/debugging
    plan_tasks: List[str]           # Tasks generated by Dynamic Planner Node

    # NEW: labels split by role, not one flat "matched_labels" list.
    #
    # hard_label_groups -> {"module": [...], "type": [...], "os": [...]}
    #   Each category can hold MULTIPLE real repo labels (e.g. module might
    #   resolve to ["terminal", "workbench-terminal", "terminal-conpty"]).
    #   Within a category, labels are OR'd in the GitHub query
    #   (label:"a","b"); across categories, they're AND'd (separate label:
    #   qualifiers). Module, type, AND os are all hard (required) filters.
    #
    # soft_labels -> symptom-related labels/terms only. NEVER used to filter
    #   the GitHub query — purely semantic context passed to the ReAct judge,
    #   since "interests/symptoms" is the one field meant to be a fuzzy
    #   semantic filter rather than a strict AND requirement.
    hard_label_groups: Dict[str, List[str]]
    soft_labels: List[str]

    # NEW: free-text search terms used ONLY when the Tree-of-Thought planner
    # selects the "keyword" branch (i.e. no reliable labels exist for one or
    # more categories, so free-text search is the winning strategy instead).
    # Empty for the "narrow"/"broad" branches, which rely on label filters.
    text_keywords: List[str]

    # NEW: records which Tree-of-Thought candidate strategies were generated,
    # their estimated result counts/scores, and which one won — purely for
    # transparency/logging, not consumed by downstream nodes.
    tot_branch_trace: List[Dict[str, Any]]
    tot_selected_branch: str  # name of the winning branch ("narrow"/"broad"/"keyword") — for metrics logging

    # NEW: whether the Fetch node had to fall back to a fully unfiltered
    # query (every hard-label category dropped) — a red flag surfaced to
    # the human reviewer in main.py (Section 12.4) since it means no
    # topical filter actually matched.
    used_unfiltered_fallback: bool

    # NEW: per-node wall-clock latency (seconds), accumulated across retries
    # for nodes invoked more than once. Section 12.3 latency metric.
    node_latencies: Dict[str, float]

    # Kept for backward compatibility / display purposes only.
    hard_labels: List[str]
    matched_labels: List[str]

    # Raw & Vector Filtered Issues
    raw_issues: List[Dict[str, Any]]
    vector_filtered_issues: List[Dict[str, Any]]  # Point 4: Post-ChromaDB issues

    # ReAct Execution & Quality State
    pooled_issues: List[Dict[str, Any]]  # Includes per-issue confidence scores
    pool_confidence_score: float         # Point 3: Average pool confidence score
    is_abstained: bool                   # Point 3: Abstention flag

    # Reflection & Summary State
    reflection_count: int           # Dynamic loop counter
    critique_feedback: str          # Feedback from reflection step
    aggregate_summary: str

    # NEW: Report Verifier Agent state — a distinct agent, distinct from the
    # report writer, that audits draft_summary against source_evidence_text
    # before aggregate_summary is finalized.
    draft_summary: str            # unverified report text from final_summary_node
    source_evidence_text: str     # the pooled-issue excerpts the draft was supposed to be grounded in
    flagged_claims: List[Dict[str, Any]]  # claims the critic judged unsupported
    report_verified: bool         # False if the critic vetoed the narrative (fell back to deterministic report)

    logs: List[str]