# agent/state.py
from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    target_os: str
    target_module: str
    symptom_type: str
    issue_type: str
    time_range_days: int

    # Point 1: Dynamic Query & Router State
    constructed_query: str          # Formulated API query string from router
    plan_tasks: List[str]           # Tasks generated by Dynamic Planner Node

    # Raw & Vector Filtered Issues
    raw_issues: List[Dict[str, Any]]
    vector_filtered_issues: List[Dict[str, Any]]  # Point 4: Post-ChromaDB issues

    # ReAct Execution & Quality State
    pooled_issues: List[Dict[str, Any]]  # Includes per-issue confidence scores
    pool_confidence_score: float         # Point 3: Average pool confidence score
    is_abstained: bool                   # Point 3: Abstention flag

    # Reflection & Summary State
    reflection_count: int           # Dynamic loop counter
    critique_feedback: str          # Feedback from reflection step
    aggregate_summary: str
    logs: List[str]