# agent/state.py
from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict):
    user_interest: str
    target_os: str
    time_range_days: int
    plan_tasks: List[str]            # Tasks generated by Planner Node
    raw_issues: List[Dict[str, Any]]
    pooled_issues: List[Dict[str, Any]]
    reflection_count: int            # Dynamic loop counter
    critique_feedback: str          # Feedback from reflection step
    aggregate_summary: str
    logs: List[str]